version: "3.9"
services:
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dataspace
    image: bitnami/postgresql:17.2.0
    ports:
      - "5432:5432"
    configs:
      - source: postgres_init_sql
        target: /docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  geodata:
    image: nginx
    ports:
      - "8088:80"
    volumes:
      - ./geodata:/usr/share/nginx/html:ro
    configs:
      - source: geodata_nginx_config
        target: /etc/nginx/nginx.conf
    restart: always

configs:
  postgres_init_sql:
    content: |
      CREATE SCHEMA IF NOT EXISTS consumer;
      CREATE SCHEMA IF NOT EXISTS provider;
  portal_config_js:
    content: |
      var config = {
        showDevices: ${PORTAL_FRONTEND_SHOW_DEVICES-false},
        showThingDescriptions: ${PORTAL_FRONTEND_SHOW_THING_DESCRIPTIONS-false},
        showQuery: ${PORTAL_FRONTEND_SHOW_QUERY-false},
        showCustomers: ${PORTAL_FRONTEND_SHOW_CUSTOMERS-false},
        showAssets: ${PORTAL_FRONTEND_SHOW_ASSETS-true},
        showPolicies: ${PORTAL_FRONTEND_SHOW_POLICIES-true},
        showContractDefinitions: ${PORTAL_FRONTEND_SHOW_CONTRACT_DEFINITIONS-true},
        showCatalog: ${PORTAL_FRONTEND_SHOW_CATALOG-true},
        showFederatedCatalog: ${PORTAL_FRONTEND_SHOW_FEDERATED_CATALOG-true},
        showContractAgreements: ${PORTAL_FRONTEND_SHOW_CONTRACT_AGREEMENTS-true},
        showTransferProcesses: ${PORTAL_FRONTEND_SHOW_TRANSFER_PROCESSES-true},
        showThingsboard: ${PORTAL_FRONTEND_SHOW_THINGSBOARD-false},
        showKeycloak: ${PORTAL_FRONTEND_SHOW_KEYCLOAK-false}
      }
  geodata_nginx_config:
    content: |
      worker_processes 1;

      events {
          worker_connections 1024;
      }

      http {
          include       mime.types;
          default_type  application/octet-stream;

          server {
              listen 80;
              server_name localhost;

              root /usr/share/nginx/html;
              index index.html;

              location ~ \.json$ {
                  default_type application/json;
              }

              location ~ \.geojson$ {
                  default_type application/json;
              }

              location / {
                  autoindex on;
                  autoindex_format json;
              }

              error_page 404 /404.html;
          }
      }
